service: marketplace
frameworkVersion: '3'
configValidationMode: error
deprecationNotificationMode: warn:summary

constructs:
  jobs:
    type: queue
    worker:
      handler: functions/sqs/handler.consumer

custom: ${file(./dependencies/myCustom.yml)}

provider: ${file(./dependencies/myProvider.yml)}

functions: ${file(./dependencies/myFunction.yml)}

resources: ${file(./dependencies/myResource.yml)}
